
ALTER TABLE TB_CATEGORIA MODIFY (CODIGO_CA NOT NULL);

ALTER TABLE TB_CATEGORIA MODIFY (DESCRIPCION_CA NOT NULL);

ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_ME NOT NULL);
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL);

-- cambiar la longitud de un tipo de dato
ALTER TABLE TB_MEDIDAS MODIFY (DESCRIPCION_ME VARCHAR2(30));

-- ELIMINAR ALGUNA COLUMNA
ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

-- ALTERAR TIPO DE DATO Y VALOR PORDEFAULT

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;
ALTER TABLE TB_CATEGORIA MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;
ALTER TABLE TB_MEDIDAS MODIFY CODIGO_ME NUMBER(3,0) DEFAULT 0;

-- AGREGAR UNA NUEVA COLUMNA 
ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR2(30);

-- AGREGAR VARIAS COLUMNAS
ALTER TABLE TB_ARTICULOS ADD (CODIGO_ME NUMBER(3,0), CODIGO_CA NUMBER(4,0));


