
ALTER TABLE TB_ARTICULOS ADD 
CONSTRAINT PK_TB_ARTICULOS PRIMARY KEY (CODIGO_AR);

ALTER TABLE TB_CATEGORIA ADD 
CONSTRAINT PK_TB_CATEGORIA PRIMARY KEY (CODIGO_CA);

ALTER TABLE TB_MEDIDAS ADD 
CONSTRAINT PK_TB_MEDIDAS PRIMARY KEY (CODIGO_ME);

